<?php

namespace App\Database\Seeds;

use CodeIgniter\Database\Seeder;

class BatchSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'tenant_id' => 1,
                'product_id' => 1,
                'batch_no' => 'RS20240430001',
                'farm_name' => '长白山林下参种植基地',
                'farm_address' => '吉林省白山市抚松县',
                'farm_area' => 50.5,
                'plant_date' => '2019-04-15',
                'harvest_date' => '2024-04-15',
                'harvest_qty' => 250.5,
                'grow_years' => 5,
                'process_method' => '低温烘干',
                'process_date' => '2024-04-18',
                'process_unit' => '长白山药材加工厂',
                'inspect_date' => '2024-04-20',
                'inspect_result' => '合格',
                'inspect_report' => 'BJ20240420001',
                'inspect_unit' => '吉林省药品检验所',
                'package_spec' => '25g/支,10支/盒',
                'package_qty' => 1000,
                'warehouse_info' => '一号仓库A区第5排',
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'tenant_id' => 1,
                'product_id' => 1,
                'batch_no' => 'RS20240430002',
                'farm_name' => '抚松人参种植合作社',
                'farm_address' => '吉林省白山市抚松县',
                'farm_area' => 35.0,
                'plant_date' => '2020-05-01',
                'harvest_date' => '2024-04-25',
                'harvest_qty' => 180.0,
                'grow_years' => 4,
                'process_method' => '自然晒干',
                'process_date' => '2024-04-28',
                'process_unit' => '抚松县药材初加工厂',
                'inspect_date' => '2024-04-29',
                'inspect_result' => '合格',
                'inspect_report' => 'BJ20240429001',
                'inspect_unit' => '白山市药品检验所',
                'package_spec' => '20g/支,12支/盒',
                'package_qty' => 800,
                'warehouse_info' => '一号仓库A区第6排',
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'tenant_id' => 1,
                'product_id' => 2,
                'batch_no' => 'SQ20240430001',
                'farm_name' => '文山三七种植示范基地',
                'farm_address' => '云南省文山州文山市',
                'farm_area' => 80.0,
                'plant_date' => '2021-03-10',
                'harvest_date' => '2024-03-10',
                'harvest_qty' => 1200.0,
                'grow_years' => 3,
                'process_method' => '机械清洗,烘干',
                'process_date' => '2024-03-12',
                'process_unit' => '文山三七加工厂',
                'inspect_date' => '2024-03-15',
                'inspect_result' => '合格',
                'inspect_report' => 'KM20240315001',
                'inspect_unit' => '云南省药品检验所',
                'package_spec' => '20头/斤,250g/袋',
                'package_qty' => 3000,
                'warehouse_info' => '二号仓库B区第3排',
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'tenant_id' => 1,
                'product_id' => 3,
                'batch_no' => 'HQ20240430001',
                'farm_name' => '内蒙古黄芪种植基地',
                'farm_address' => '内蒙古自治区包头市固阳县',
                'farm_area' => 120.0,
                'plant_date' => '2022-04-01',
                'harvest_date' => '2024-04-01',
                'harvest_qty' => 2000.0,
                'grow_years' => 2,
                'process_method' => '去芦,切片,干燥',
                'process_date' => '2024-04-03',
                'process_unit' => '内蒙古药材加工厂',
                'inspect_date' => '2024-04-05',
                'inspect_result' => '合格',
                'inspect_report' => 'NM20240405001',
                'inspect_unit' => '内蒙古自治区药品检验所',
                'package_spec' => '特级片,250g/袋',
                'package_qty' => 4000,
                'warehouse_info' => '三号仓库C区第1排',
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'tenant_id' => 2,
                'product_id' => 6,
                'batch_no' => 'TRT-NHQXW202404001',
                'farm_name' => '同仁堂原料药材种植基地',
                'farm_address' => '北京市怀柔区',
                'farm_area' => 100.0,
                'plant_date' => '2023-01-01',
                'harvest_date' => '2024-02-01',
                'harvest_qty' => 500.0,
                'grow_years' => 1,
                'process_method' => '古法炮制',
                'process_date' => '2024-02-15',
                'process_unit' => '同仁堂制药厂',
                'inspect_date' => '2024-02-20',
                'inspect_result' => '合格',
                'inspect_report' => 'BJTRT20240220001',
                'inspect_unit' => '北京市药品检验所',
                'package_spec' => '每丸3g,10丸/盒',
                'package_qty' => 5000,
                'warehouse_info' => '同仁堂北京库房',
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'tenant_id' => 2,
                'product_id' => 7,
                'batch_no' => 'TRT-AGNHW202404001',
                'farm_name' => '同仁堂牛黄培育中心',
                'farm_address' => '北京市大兴区',
                'farm_area' => 50.0,
                'plant_date' => '2023-01-01',
                'harvest_date' => '2024-03-01',
                'harvest_qty' => 200.0,
                'grow_years' => 1,
                'process_method' => '传统工艺炮制',
                'process_date' => '2024-03-10',
                'process_unit' => '同仁堂制药厂',
                'inspect_date' => '2024-03-15',
                'inspect_result' => '合格',
                'inspect_report' => 'BJTRT20240315001',
                'inspect_unit' => '国家药品检验所',
                'package_spec' => '每丸3g,10丸/盒',
                'package_qty' => 3000,
                'warehouse_info' => '同仁堂北京库房',
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ],
            [
                'tenant_id' => 3,
                'product_id' => 8,
                'batch_no' => 'YNBY-F202404001',
                'farm_name' => '云南白药原材料种植基地',
                'farm_address' => '云南省昆明市呈贡区',
                'farm_area' => 200.0,
                'plant_date' => '2023-03-01',
                'harvest_date' => '2024-03-01',
                'harvest_qty' => 3000.0,
                'grow_years' => 1,
                'process_method' => '秘方炮制工艺',
                'process_date' => '2024-03-10',
                'process_unit' => '云南白药集团制药厂',
                'inspect_date' => '2024-03-20',
                'inspect_result' => '合格',
                'inspect_report' => 'KMYNBY20240320001',
                'inspect_unit' => '云南省药品检验所',
                'package_spec' => '4g/瓶,10瓶/盒',
                'package_qty' => 10000,
                'warehouse_info' => '云南白药总部库房',
                'status' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ]
        ];

        foreach ($data as $item) {
            $this->db->table('batches')->insert($item);
        }
    }
}
